MvcProjectCamp/Controllers/WriterPanelController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using PagedList;
using PagedList.Mvc;
using ValidationResult = FluentValidation.Results.ValidationResult;


namespace MvcProjectCamp.Controllers
{
    public class WriterPanelController : Controller
    { 
         HeadingManager hm = new HeadingManager(new EfHeadingDal());
         Context c = new Context();
         CategoryManager cm = new CategoryManager(new EfCategoryDal());
         WriterManager wm = new WriterManager(new EfWriterDal());


        // GET: WriterPanel

        



        [HttpGet]
        public ActionResult WriterProfile(int id = 0)
        {
           string p = (string)Session["WriterMail"];
    
            id = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterId).FirstOrDefault();

            var writerValue = wm.GetByWriterId(id);


           


            return View(writerValue);
        }

        [HttpPost]
        public ActionResult WriterProfile(Writer p)
        {
            WriterValidator writerValidator = new WriterValidator();
            ValidationResult results = writerValidator.Validate(p);

            if (results.IsValid)
            {
                wm.WriterUpdate(p);



                ViewBag.result = "Güncellendi.";

                

                return View("WriterProfile" ,p);
            }
             
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                }
            }

            return View();
        }






        public ActionResult MyHeading(string p)
        {
           
            p = (string)Session["WriterMail"];
          var  writerIdInfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterId).FirstOrDefault();

          


            var myHeadingValues = hm.GetListByWriter(writerIdInfo);
            return View(myHeadingValues);
        }



        [HttpGet]
        public ActionResult NewHeading(string p)
        {
                          
            List<SelectListItem> valueCategory = (from c in cm.GetCategoryList() //Listeleme 
                                                  select new SelectListItem()
                                                  {
                                                      Text = c.CategoryName,
                                                      Value = c.CategoryId.ToString()

                                                  }).ToList();
            @ViewBag.vlc = valueCategory;
            return View();
        }


        [HttpPost]
        public ActionResult NewHeading(Heading p)
        {

            string m = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == m).Select(y => y.WriterId).FirstOrDefault();
           
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterId = writerIdInfo;
            p.HeadingStatus = true;

            hm.HeadingAddBl(p);


            return RedirectToAction("MyHeading");

        }
        [HttpGet]
        public ActionResult EditMyHeading(int id)
        {

            List<SelectListItem> valueCategory = (from c in cm.GetCategoryList() //Listeleme 
                select new SelectListItem()
                {
                    Text = c.CategoryName,
                    Value = c.CategoryId.ToString()

                }).ToList();
            ViewBag.vlc = valueCategory;
            var headingValue = hm.GetByHeadingId(id);

            return View(headingValue);
        }
        
        [HttpPost]
        public ActionResult EditMyHeading(Heading h)
        {

            string m = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == m).Select(y => y.WriterId).FirstOrDefault();

            h.WriterId = writerIdInfo;



            h.HeadingId = c.Headings.Where(x=>x.WriterId == h.WriterId).Select(y=>y.HeadingId).FirstOrDefault();

            hm.HeadingUpdate(h);

            return RedirectToAction("MyHeading");
        }



        public ActionResult DeleteHeading(int id)
        {

            var headingValue = hm.GetByHeadingId(id);

            switch (headingValue.HeadingStatus)
            {
                case true:
                    headingValue.HeadingStatus = false;
                    break;
                case false:
                    headingValue.HeadingStatus = true;
                    break;
            }


            hm.HeadingDelete(headingValue);

            return RedirectToAction("MyHeading");
        }
        public ActionResult AllHeading(int p = 1)
        {

            var headingsList = hm.GetHeadingList().ToPagedList(p, 4);

            return View(headingsList);
        }


       

   

    }
}

MvcProjectCamp/Views/WriterPanel/AllHeading.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc

@model PagedList.IPagedList<Heading>


@{
    ViewBag.Title = "AllHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


@section css{
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    


    <!-- PagedList Style or new{p}), new PagedListRenderOptions{LiElementClasses = new List<string>{"page-link"}}) -->
    <link rel="stylesheet" href="~/Content/PagedList.css">
}



@{ string genderResult = "AdminLTELogo.png";}
@{ string badgeResults = "badge badge-success";}
@{ string headingStatusClassResults = "pasive-border";}
@{ string headingStatusClassResultsNand = "btn btn-secondary";}
@{ string statusResult = "Belirsiz";}
@{ string statusResultNand = "Belirsiz";}
@{ string fontStatusResultColor = "Belirsiz";}

  
    

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" style="font-weight:bold">Başlık İşlemleri Listesi</h3>


                <div class="card-tools">
                    <a href="~/WriterPanel/NewHeading" class="btn btn-app" style="padding-top: 5px;height: 30px;">
                        <i class="fas fa-plus" style="position: relative; margin-right:3px ; float: left; " ></i>  Yeni Başlık Ekle
                    </a>
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 21%">
                                Başlık Adı
                            </th>
                            <th style="width: 1%; font-size: 14px !important;">
                                Profil Resmi
                            </th>
                            <th style="width: 20%;">
                                Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                         
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {



                            if (item.Writer.Gender == "K")
                            {
                                genderResult = "avatar2.png";
                            }

                            if (item.Writer.Gender == "E")
                            {
                                genderResult = "avatar5.png";
                            }

                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                badgeResults = "badge badge-info";
                            }

                            if (item.Category.CategoryName == "Yazılım")
                            {
                                badgeResults = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Spor")
                            {
                                badgeResults = "badge badge-warning";
                            }

                            if (item.Category.CategoryName == "Film")
                            {
                                badgeResults = "badge badge-secondary";
                            }






                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @item.HeadingDate.ToString("dd-MMM-yyyy")
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline" style="text-align: center">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="~/AdminLTE/dist/img/@genderResult">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    <small>Yazar İçerik Kota</small>
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-green" role="progressbar" aria-valuenow="57" aria-valuemin="0" aria-valuemax="100" style="width: @item.Writer.Headings.Count%;">
                                        </div>
                                    </div>
                                    <a>
                                        @item.Writer.WriterName @item.Writer.WriterSurName
                                    </a>
                                </td>
                                


                                <td class="project-state">
                                    <span class="@badgeResults">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-state">
                                    
                                    <div style="float: left; padding: 3px; ">
                                        <a type="button" class="btn btn-block btn-outline-secondary btn-sm" href="~/WriterPanelContent/AddContent/@item.HeadingId">
                                            <i class="fas fa-pencil-alt" style="padding: 3px;">
                                            </i>Bu Başlığa Yorum Ekle
                                        </a>
                                    </div>

                                    <div style="float: left; padding: 3px;">
                                        <a type="button" class="btn btn-block btn-outline-info btn-sm" href="~/Default/Headings/@item.HeadingId">
                                            <i class="fas fa-folder" style="padding: 3px;">
                                            </i>Yazılar
                                        </a>
                                    </div>




                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

<!-- ./wrapper -->




    @Html.PagedListPager((IPagedList)Model,p=>Url.Action("AllHeading",new {p}))



@section script
{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}

MvcProjectCamp/Views/WriterPanel/EditMyHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "EditMyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}



@section css{
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
}


<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title" style="float: none !important; text-align: center; ">Başlık Düzenleme Sayfası</h3>
    </div>



    @using (Html.BeginForm("EditMyHeading", "WriterPanel", FormMethod.Post))
    {

<div class="form-group" style="padding: 50px;">

   

    @Html.Label("Başlık Adı :")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName, "", new { @class = "text-danger" })
    <br />

    @Html.Label("Başlık Tarihi :")
    @Html.TextBoxFor(x => x.HeadingDate, "", new { @class = "form-control" })
    

    <br />
    @Html.Label("Kategori Adı :")
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })

    <br />




    <button class="btn btn-success" style="  margin: 0;position: relative;top: 50%;left: 50%;-ms-transform: translate(-50%, -50%);transform: translate(-50%, 77%);">Değişiklikleri Kaydet</button>

</div>
    }
    
    
    
  

</div>



@section script
{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}

MvcProjectCamp/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


@section css{   <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">}



<div class="card card-primary">


    <div class="card-header">
        <h3 class="card-title" style="float: none !important; text-align: center; font-weight:bold;"><i class=" nav-icon fas fa-newspaper" style="margin-right: 5px; "> </i>Yeni Başlık Ekleme Sayfası</h3>
    </div>
    @using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
    {<div class="form-group" style="padding: 50px;">
            @Html.Label("Başlık Adı:")
            @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.HeadingName, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Kategoryi Id:")
            @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CategoryId, "", new { @class = "text-danger" })
            <br />

           

            <button class="btn btn-success" type="submit" style="margin-left: 50%;"> Başlık Ekle</button>

        </div>}
</div>


@ViewBag.m


@section script{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
   
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}

MvcProjectCamp/Views/WriterPanel/WriterProfile.cshtml
@model EntityLayer.Concrete.Writer

@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@section css{
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
}




  @using (Html.BeginForm("WriterProfile", "WriterPanel", FormMethod.Post))
        {
             

        <div class="form-group" style="padding: 50px;">
            @Html.Label("Yazar Id:")
            @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterId, "", new { @class = "text-danger" })

            <br /> <br />
            @Html.Label("Yazar Adı :")
            @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Soyadı :")
            @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterSurName, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Cinsiyet :")
            @Html.TextBoxFor(x => x.Gender, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Fotoğraf URL :")
            @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterImage, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Mail Adresi :")
            @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterMail, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Şifresi :")
            @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterPassword,"" ,new {@class = "text-danger"  })
            <br />

            @Html.Label("Yazar Unvanı :")
            @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterTitle, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Hakkında Bilgi :")
            @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterAbout, "", new { @class = "text-danger" })
            <br />
            
            <p>@ViewBag.result</p>
            

            <button class="btn btn-success" style="margin: auto !important;">Değişiklikleri Kaydet</button>

        </div>

          
        }


@section script
{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    @*<script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>*@
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}