MvcProjectCamp/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;


namespace MvcProjectCamp.Controllers
{
    public class WriterController : Controller
    {
        WriterManager wm = new WriterManager(new EfWriterDal());
        // GET: Writer


        public ActionResult WriterList()
        {
            var writerValues = wm.GetWriterList();
            return View(writerValues);
        }
    }
}

MvcProjectCamp/Controllers/WritersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.Abstract;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;


namespace MvcProjectCamp.Controllers
{
    public class WritersController : Controller
    {



        WriterManager wm = new WriterManager(new EfWriterDal());
        WriterValidator writerValidator = new WriterValidator();
        // GET: Writer


        public ActionResult WritersList()
        {

            var writerValues = wm.GetWriterList();
           
            return View(writerValues);
        }

       

        [HttpGet]
        public ActionResult AddWriter()
        {
            return View();
        }

       


        [HttpPost]
        public ActionResult AddWriter(Writer p)
        {
            

            ValidationResult results = writerValidator.Validate(p);
            if (results.IsValid)
            {
                wm.WriterAddBl(p);
                return RedirectToAction("WritersList");

            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                }
            }

            return View();
        }

        [HttpGet]
        public ActionResult EditWriter(int id)
        {

            var writervalue = wm.GetByWriterId(id);
            return View(writervalue);
        }

        [HttpPost]
        public ActionResult EditWriter(Writer p)
        {

           
                ValidationResult results = writerValidator.Validate(p);
                if (results.IsValid)
                {
                    wm.WriterUpdate(p);
                    return RedirectToAction("WritersList");

                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                    }

                    return View();
                }
           

        }

       

    }
}

MvcProjectCamp/Views/Writers/AddWriter.cshtml
@model EntityLayer.Concrete.Writer


@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
}


<section>


    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title" style="float: none !important; text-align: center; ">Yeni Yazar Ekleme Sayfası</h3>
        </div>




        @using (Html.BeginForm("AddWriter", "Writers", FormMethod.Post))
        {
            <div class="form-group" style="padding: 50px;">
                @Html.Label("Yazar Adı:")
                @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.WriterName)

                <br />

                @Html.Label("Yazarın Soyadını Giriniz :")
                @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.WriterSurName)
                <br />
                
                @Html.Label("Yazarın Fotoğraf URL'sini Giriniz :")
                @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
             
                <br />
                
                
                @Html.Label("Yazarın Mail Adresini Giriniz :")
                @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                
                <br />
                
                @Html.Label("Yazarın Şifresini Giriniz :")
                @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
       
                <br />
                
                @Html.Label("Yazar Hakkında Bilgi Giriniz :")
                @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
               
                <br />
                
                @Html.Label("Yazarın Unvanı Giriniz :")
                @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.WriterTitle)
                <br />
                
                
                @Html.Label("Yazarın Cinsiyetini Bilgi Giriniz(E - K Şeklinde :")
                @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
               
                <br />
                
                @Html.Label("Yazarın Kimlik Durumunu Giriniz(True - False :")
                @Html.TextBoxFor(x => x.WriterStatus, new { @class = "form-control" })
               
                <br />
                

              
                <button class="btn bg-gradient-info" type="submit" style="margin: 0 auto;display: block; ">
                    <i class="fas fa-save"></i> Yazarı Ekle
                </button>


            </div>

          
        }
    </div>
</section>
@section script
{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}

MvcProjectCamp/Views/Writers/EditWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "EditWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
}
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title" style="float: none !important; text-align: center; ">Yazar Düzenleme Sayfası</h3>
    </div>



    @using (Html.BeginForm("EditWriter", "Writers", FormMethod.Post))
    {

        <div class="form-group" style="padding: 50px;">
            @Html.Label("Yazar Id:")
            @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterId, "", new { @class = "text-danger" })

            <br /> <br />
            @Html.Label("Yazar Adı :")
            @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Soyadı :")
            @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterSurName, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Cinsiyet :")
            @Html.TextBoxFor(x => x.Gender, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Fotoğraf URL :")
            @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterImage, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Mail Adresi :")
            @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterMail, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Şifresi :")
            @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterPassword,"" ,new {@class = "text-danger"  })
            <br />

            @Html.Label("Yazar Unvanı :")
            @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterTitle, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Hakkında Bilgi :")
            @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterAbout, "", new { @class = "text-danger" })
            <br />

            <button class="btn btn-success" style="margin: auto !important;">Değişiklikleri Kaydet</button>

        </div>
    }

</div>

@section script
{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}

MvcProjectCamp/Views/Writers/WriterList.cshtml
@using EntityLayer.Concrete
@model List<Writer>


@{
    ViewBag.Title = "WriterList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper"  style="padding : 30px">
        <!-- Main content -->
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                   Yazar: @item.WriterId
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.WriterName @item.WriterSurName</b></h2>
                                            <p class="text-muted text-sm"><b>About: </b> - </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Mail: @item.WriterMail</li>
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: - </li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="~/AdminLTE/dist/img/user2-160x160.jpg" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="#" class="btn btn-sm btn-danger">
                                            <i class="fas fa-comments"> Yazarın Başlıkları</i>
                                        </a>
                                        <a href="#" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Profili Düzenle
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <!-- /.card-body -->
            <!-- /.card -->
            <!-- /.content -->
        </div>

        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>

MvcProjectCamp/Views/Writers/WritersList.cshtml
@using EntityLayer.Concrete
@model List<Writer>


@{
    ViewBag.Title = "Admin Paneli | Yazar Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section css{
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper" style="padding : 3px">
        <!-- Main content -->
        <!-- Default box -->
        <div class="card card-solid" style="max-width: 100%;">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch" style="margin: auto;width: 98%; margin: auto; ">
                    @foreach (var item in Model)
                    {

                       

                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch" style="max-width: 387px !important;" >
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    Unvanı: @item.WriterTitle
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.WriterName @item.WriterSurName</b></h2>
                                            <p class="text-muted text-sm"><b>Hakkında: </b> @item.WriterAbout </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Mail: @item.WriterMail</li>
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: - </li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="~/AdminLTE/dist/img/user2-160x160.jpg" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">

                                    <div class="text-right">
                                    <a href="#" class="btn btn-sm bg-danger">
                                        <i class="fas fa-comments"></i> Yazarın Başlıkları

                                    </a>
                                    <a  href="/Writers/EditWriter/@item.WriterId"class="btn btn-sm btn-primary">
                                        <i class="fas fa-user"></i> Profili Düzenle
                                    </a>
                                </div></div>
                               
                            </div>

                        </div>
                        
                             }
                    
                </div>
                <div style="text-align: center;margin: auto">
                    <a href="~/Writers/AddWriter" class="btn btn-primary">Yeni Yazar Ekle</a>

                    <br />
                    <br />
                </div>
            </div>
            <!-- /.card-body -->
            <!-- /.card -->
            <!-- /.content -->
        </div>

        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
  
    <!-- Bootstrap 4 -->
    <!--<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>-->
    <!-- AdminLTE App -->
    <!--<script src="~/AdminLTE/dist/js/adminlte.min.js"></script>-->
    <!-- AdminLTE for demo purposes -->
    <!--<script src="~/AdminLTE/dist/js/demo.js"></script>-->
</body>
</html>
@section script
{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}