MvcProjectCamp/Controllers/HeadingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;

namespace MvcProjectCamp.Controllers
{
    

    public class HeadingController : Controller
    {

        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        // GET: Headings
        public ActionResult HeadingLists()
        {
            var headingValues = hm.GetHeadingList();

            return View(headingValues);
        }
        [HttpGet]
        public ActionResult AddHeading()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading h)
        {
         
                hm.HeadingAddBl(h);
                return RedirectToAction("HeadingLists");
           



            return View();
        }

    }
}

MvcProjectCamp/Controllers/HeadingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MvcProjectCamp.Controllers
{


    public class HeadingsController : Controller
    {

        HeadingManager hm = new HeadingManager(new EfHeadingDal());

        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal()); // GET: Headings


        public ActionResult HeadingsList()
        {
            var headingValues = hm.GetHeadingList();

            ViewBag.Checked = "Pasif";

            return View(headingValues);
        }



        [HttpPost]
        public ActionResult HeadingsList(Heading head)
        {
            
            return View(head);
        }



        [HttpGet]
        public ActionResult AddHeading()
        {

            List<SelectListItem> valueCategory = (from c in cm.GetCategoryList() //Listeleme 
                                                  select new SelectListItem()
                                                  {
                                                      Text = c.CategoryName,
                                                      Value = c.CategoryId.ToString()

                                                  }).ToList();

            List<SelectListItem> valueWriter = (from w in wm.GetWriterList()
                                                select new SelectListItem()
                                                {
                                                    Text = w.WriterName + " " + w.WriterSurName,
                                                    Value = w.WriterId.ToString()

                                                }).ToList();

            ViewBag.vlw = valueWriter;
            ViewBag.vlc = valueCategory;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading h)
        {
            h.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAddBl(h);
            return RedirectToAction("HeadingsList");
            
        }



       


        [HttpGet]
        public ActionResult EditHeading(int id)
        {

            List<SelectListItem> valueCategory = (from c in cm.GetCategoryList() //Listeleme 
                select new SelectListItem()
                {
                    Text = c.CategoryName,
                    Value = c.CategoryId.ToString()

                }).ToList();
            ViewBag.vlc = valueCategory;
            var headingValue = hm.GetByHeadingId(id);

            return View(headingValue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading h)
        {

            hm.HeadingUpdate(h);

            return RedirectToAction("HeadingsList");
        }


        
        public ActionResult DeleteHeading(int id)
        {

            var headingValue = hm.GetByHeadingId(id);

            switch (headingValue.HeadingStatus)
            {
                case true:
                    headingValue.HeadingStatus = false;
                    break;
                case false:
                    headingValue.HeadingStatus = true;
                    break;
            }

          
            hm.HeadingDelete(headingValue);

            return RedirectToAction("HeadingsList");
        }


    }
}

MvcProjectCamp/Views/Headings/AddHeading.cshtml
@model EntityLayer.Concrete.Heading


@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@section css{   <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">}



<div class="card card-primary">


    <div class="card-header">
        <h3 class="card-title" style="float: none !important; text-align: center; font-weight:bold;"><i class=" nav-icon fas fa-newspaper" style="margin-right: 5px; "> </i>Yeni Başlık Ekleme Sayfası</h3>
    </div>
    @using (Html.BeginForm("AddHeading", "Headings", FormMethod.Post))
    {<div class="form-group" style="padding: 50px;">
            @Html.Label("Başlık Adı:")
            @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.HeadingName, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Kategoryi Id:")
            @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CategoryId, "", new { @class = "text-danger" })
            <br />

            @Html.Label("Yazar Id:")
            @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterId, "", new { @class = "text-danger" })
            <br />


            <button class="btn btn-success"  type="submit" style="margin: 0 auto;display: block; "> Başlık Ekle</button>

        </div>}
</div>


@section script{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
   
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}

MvcProjectCamp/Views/Headings/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
}


<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title" style="float: none !important; text-align: center; ">Başlık Düzenleme Sayfası</h3>
    </div>



    @using (Html.BeginForm("EditHeading", "Headings", FormMethod.Post))
    {

<div class="form-group" style="padding: 50px;">

    @Html.Label("Başlık ID :")
    @Html.TextBoxFor(x => x.HeadingId, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingId, "", new { @class = "text-danger" })
    <br />

    @Html.Label("Başlık Adı :")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName, "", new { @class = "text-danger" })
    <br />

    @Html.Label("Başlık Tarihi :")
    @Html.TextBoxFor(x => x.HeadingDate, "", new { @class = "form-control" })

    <br />

    @Html.Label("Yazar Adı :")
    @Html.TextBoxFor(x => x.WriterId , "", new { @class = "form-control" })

    <br />
    @Html.Label("Kategori Adı :")
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })

    <br />




    <button class="btn btn-success" style="  margin: 0;position: relative;top: 50%;left: 50%;-ms-transform: translate(-50%, -50%);transform: translate(-50%, 77%);">Değişiklikleri Kaydet</button>

</div>
    }
    
    
    
  

</div>



@section script
{
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/AdminLTE/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="/AdminLTE/plugins/moment/moment.min.js"></script>
    <script src="/AdminLTE/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/AdminLTE/dist/js/pages/dashboard.js"></script>}

MvcProjectCamp/Views/Headings/HeadingsList.cshtml
@using EntityLayer.Concrete
@model List<Heading>

@{
    ViewBag.Title = "Admin Paneli | Başlık Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{ string genderResult = "AdminLTELogo.png";}
@{ string badgeResults = "badge badge-success";}
@{ string headingStatusClassResults = "pasive-border";}
@{ string headingStatusClassResultsNand = "btn btn-secondary";}
@{ string statusResult = "Belirsiz";}
@{ string statusResultNand = "Belirsiz";}
@{ string fontStatusResultColor = "Belirsiz";}

headingStatusClassResultsNand    headingStatusClassResultsNand
    @section css{
        <!-- Google Font: Source Sans Pro -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">}


    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" style="font-weight:bold">Başlık İşlemleri Listesi</h3>


                <div class="card-tools">
                    <a href="~/Headings/AddHeading" class="btn btn-app" style="text-align: right; display: ruby; padding: 5px; vertical-align: baseline;">
                        <i class="fas fa-plus" style="position: relative;top: 3px"></i>  Yeni Başlık Ekle
                    </a>
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 21%">
                                Başlık Adı
                            </th>
                            <th style="width: 0%; font-size: 14px !important;">
                                Profil Resmi
                            </th>
                            <th style="width: 20%;">
                                Yazar
                            </th>
                            <th style="width: 6%;" class="text-center">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 33%;">
                                İşlemler
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {



                            if (item.Writer.Gender == "K")
                            {
                                genderResult = "avatar2.png";
                            }

                            if (item.Writer.Gender == "E")
                            {
                                genderResult = "avatar5.png";
                            }

                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                badgeResults = "badge badge-info";
                            }

                            if (item.Category.CategoryName == "Yazılım")
                            {
                                badgeResults = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Spor")
                            {
                                badgeResults = "badge badge-warning";
                            }

                            if (item.Category.CategoryName == "Film")
                            {
                                badgeResults = "badge badge-secondary";
                            }



                            switch (item.HeadingStatus)
                            {
                                case true:

                                    statusResult = "Aktif";
                                    statusResultNand = "Pasif Yap";
                                    headingStatusClassResults = "nav-icon far fa-circle text-success";
                                    headingStatusClassResultsNand = "btn btn-block btn-outline-danger btn-sm";
                                    fontStatusResultColor = "text-success";

                                    break;

                                case false:
                                    statusResult = "Pasif";
                                    statusResultNand = "Aktif Yap";
                                    headingStatusClassResults = "nav-icon far fa-circle text-danger";
                                    headingStatusClassResultsNand = "btn btn-block btn-outline-success btn-sm";
                                    fontStatusResultColor = "text-danger";
                                    break;

                            }




                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @item.HeadingDate.ToString("dd-MMM-yyyy")
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline" style="text-align: center">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="~/AdminLTE/dist/img/@genderResult">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    <small>Yazar İçerik Kota</small>
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-green" role="progressbar" aria-valuenow="57" aria-valuemin="0" aria-valuemax="100" style="width: @item.Writer.Headings.Count%;">
                                        </div>
                                    </div>
                                    <a>
                                        @item.Writer.WriterName @item.Writer.WriterSurName
                                    </a>
                                </td>

                                <td style="text-align: center !important; ">

                                    <i class="@headingStatusClassResults"></i> <p class="@fontStatusResultColor" style="float: right; margin-top:-1px; margin-bottom: -1rem;margin-right: 10px;">
                                        @statusResult
                                    </p>




                                </td>



                                <td class="project-state">
                                    <span class="@badgeResults">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-state">

                                    <div style="float: left; padding: 3px;">
                                        <a type="button" class="btn btn-block btn-outline-info btn-sm" href="~/Headings/EditHeading/@item.HeadingId">
                                            <i class="fas fa-folder" style="padding: 3px;">
                                            </i>İçerik Bilgisi
                                        </a>
                                    </div>

                                    <div style="float: left; padding: 3px; ">
                                        <a type="button" class="btn btn-block btn-outline-secondary btn-sm" href="~/Headings/EditHeading/@item.HeadingId">
                                            <i class="fas fa-pencil-alt" style="padding: 3px;">
                                            </i>Düzenle
                                        </a>
                                    </div>

                                    <div style="float: left; padding: 3px; ">
                                        <a class="@headingStatusClassResultsNand" href="~/Headings/DeleteHeading/@item.HeadingId">
                                            <i class="icon fas fa-exclamation-triangle" style="padding: 3px;"></i>@statusResultNand
                                        </a>
                                    </div>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

<!-- ./wrapper -->



   @section script{
       <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
       <!-- Bootstrap 4 -->
       <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
       <!-- AdminLTE App -->
       <script src="/AdminLTE/dist/js/adminlte.min.js"></script>
       <!-- AdminLTE for demo purposes -->
       <script src="/AdminLTE/dist/js/demo.js"></script>
   }